import { Lead } from "@/features/crm/types/Lead";

export const LEADS: Lead[] = [
  {
    id: "1",
    name: "John Smith",
    company: "Tech Corp",
    email: "john@techcorp.com",
    phone: "+1-555-0123",
    status: "Qualified",
    priority: "High",
    value: 25000,
    source: "Website",
    assignedTo: "Sarah Johnson",
    score: 85,
    lastContact: "2 hours ago",
    nextFollowUp: "Tomorrow 10:00 AM",
    notes: "Interested in enterprise solution. Budget confirmed.",
    tags: ["enterprise", "tech", "high-value"],
    createdAt: "2024-01-15",
    updatedAt: "2024-01-20",
  },
  {
    id: "2",
    name: "Sarah Johnson",
    company: "Design Studio",
    email: "sarah@designstudio.com",
    phone: "+1-555-0124",
    status: "New",
    priority: "Medium",
    value: 15000,
    source: "Referral",
    assignedTo: "Mike Wilson",
    score: 72,
    lastContact: "4 hours ago",
    nextFollowUp: "Next week",
    notes: "Looking for design services.",
    tags: ["design", "creative"],
    createdAt: "2024-01-18",
    updatedAt: "2024-01-20",
  },
  {
    id: "3",
    name: "Mike Wilson",
    company: "Marketing Plus",
    email: "mike@marketingplus.com",
    phone: "+1-555-0125",
    status: "Proposal",
    priority: "High",
    value: 45000,
    source: "Social Media",
    assignedTo: "John Smith",
    score: 90,
    lastContact: "1 day ago",
    nextFollowUp: "Friday 2:00 PM",
    notes: "Ready to move forward with proposal.",
    tags: ["marketing", "enterprise", "high-value"],
    createdAt: "2024-01-10",
    updatedAt: "2024-01-19",
  },
];
