import { Product } from "@/types/Product";

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Wireless Bluetooth Headphones",
    description: "High-quality wireless headphones with noise cancellation",
    price: 129.99,
    originalPrice: 159.99,
    category: "Electronics",
    brand: "AudioTech",
    image: "/images/products/wireless-headphone.jpg",
    stock: 45,
    status: "in-stock",
    rating: 4.5,
    reviews: 128,
    createdAt: "2024-01-15",
    updatedAt: "2024-01-20",
  },
  {
    id: "2",
    name: "Smart Fitness Watch",
    description: "Track your health and fitness goals",
    price: 199.99,
    category: "Wearables",
    brand: "FitTech",
    image: "/images/products/smart-fitness-watch.jpg",
    stock: 12,
    status: "low-stock",
    rating: 4.2,
    reviews: 89,
    createdAt: "2024-01-10",
    updatedAt: "2024-01-18",
  },
  {
    id: "3",
    name: "Organic Cotton T-Shirt",
    description: "Comfortable and eco-friendly cotton t-shirt",
    price: 29.99,
    category: "Clothing",
    brand: "EcoWear",
    image: "/images/products/organic-cotton-t-shirt.jpg",
    stock: 0,
    status: "out-of-stock",
    rating: 4.7,
    reviews: 256,
    createdAt: "2024-01-05",
    updatedAt: "2024-01-22",
  },
  {
    id: "4",
    name: "Portable Power Bank",
    description: "10000mAh portable charger for all devices",
    price: 49.99,
    originalPrice: 69.99,
    category: "Electronics",
    brand: "PowerTech",
    image: "/images/products/portable-power-bank.jpg",
    stock: 78,
    status: "in-stock",
    rating: 4.3,
    reviews: 156,
    createdAt: "2024-01-12",
    updatedAt: "2024-01-19",
  },
  {
    id: "5",
    name: "Stainless Steel Water Bottle",
    description: "Insulated water bottle keeps drinks cold for 24 hours",
    price: 34.99,
    category: "Home & Garden",
    brand: "HydroLife",
    image: "/images/products/stainless-steel-water-bottle.jpg",
    stock: 23,
    status: "low-stock",
    rating: 4.6,
    reviews: 203,
    createdAt: "2024-01-08",
    updatedAt: "2024-01-21",
  },
  {
    id: "6",
    name: "Wireless Gaming Mouse",
    description: "High-precision gaming mouse with RGB lighting",
    price: 79.99,
    category: "Electronics",
    brand: "GameTech",
    image: "/images/products/wireless-gaming-mouse.jpg",
    stock: 34,
    status: "in-stock",
    rating: 4.4,
    reviews: 167,
    createdAt: "2024-01-14",
    updatedAt: "2024-01-20",
  },
];

export const PRODUCT_CATEGORIES = [
  "All Categories",
  "Electronics",
  "Clothing",
  "Wearables",
  "Home & Garden",
  "Sports",
  "Books",
  "Beauty",
];

export const PRODUCT_BRANDS = [
  "All Brands",
  "AudioTech",
  "FitTech",
  "EcoWear",
  "PowerTech",
  "HydroLife",
  "GameTech",
  "SmartHome",
];
