import { Product } from "@/shared/types/Product";

export const ITEMS_PER_PAGE = 7;

export const TIME_FILTERS = ["Today", "This Week", "This Month", "This Year"];

export const TOP_SELLING_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Smart Watch",
    description: "Advanced fitness tracking smartwatch",
    price: 199.99,
    category: "Wearables",
    brand: "FitTech",
    image: "/images/products/smartwatch.jpg",
    stock: 45,
    itemId: "ARP-1217",
    itemsSold: 953,
    sales: 90954,
    status: "in-stock",
    rating: 4.5,
    reviews: 128,
    createdAt: "2024-01-15",
    updatedAt: "2024-01-20",
    color: "black",
  },
  {
    id: "2",
    name: "Mobile Phone",
    description: "Latest smartphone with advanced features",
    price: 899.99,
    category: "Electronics",
    brand: "PhoneTech",
    image: "/images/products/mobilephone.jpg",
    stock: 23,
    itemId: "ARP-9513",
    itemsSold: 876,
    sales: 85648,
    status: "low-stock",
    rating: 4.3,
    reviews: 89,
    createdAt: "2024-01-10",
    updatedAt: "2024-01-18",
    color: "black",
  },
  {
    id: "3",
    name: "Laptop Device",
    description: "High-performance laptop for work and gaming",
    price: 1299.99,
    category: "Electronics",
    brand: "LaptopTech",
    image: "/images/products/laptop.jpg",
    stock: 12,
    itemId: "ARP-7531",
    itemsSold: 823,
    sales: 79852,
    status: "low-stock",
    rating: 4.7,
    reviews: 156,
    createdAt: "2024-01-05",
    updatedAt: "2024-01-22",
    color: "black",
  },
  {
    id: "4",
    name: "Black T-Shirt",
    description: "Premium cotton black t-shirt",
    price: 29.99,
    category: "Clothing",
    brand: "EcoWear",
    image: "/images/products/tshirt.jpg",
    stock: 78,
    itemId: "ARP-3579",
    itemsSold: 743,
    sales: 73624,
    status: "in-stock",
    rating: 4.2,
    reviews: 203,
    createdAt: "2024-01-12",
    updatedAt: "2024-01-19",
    color: "black",
  },
  {
    id: "5",
    name: "Headphones",
    description: "Wireless noise-cancelling headphones",
    price: 129.99,
    category: "Electronics",
    brand: "AudioTech",
    image: "/images/products/headphones.jpg",
    stock: 34,
    itemId: "ARP-4826",
    itemsSold: 693,
    sales: 65973,
    status: "in-stock",
    rating: 4.6,
    reviews: 167,
    createdAt: "2024-01-14",
    updatedAt: "2024-01-20",
    color: "black",
  },
  {
    id: "6",
    name: "Hand Watch",
    description: "Classic analog hand watch",
    price: 89.99,
    category: "Wearables",
    brand: "TimeTech",
    image: "/images/products/handwatch.jpg",
    stock: 56,
    itemId: "ARP-1265",
    itemsSold: 654,
    sales: 42455,
    status: "in-stock",
    rating: 4.4,
    reviews: 134,
    createdAt: "2024-01-08",
    updatedAt: "2024-01-21",
    color: "black",
  },
  {
    id: "7",
    name: "Gaming Mouse",
    description: "High-precision gaming mouse with RGB",
    price: 79.99,
    category: "Electronics",
    brand: "GameTech",
    image: "/images/products/gamingmouse.jpg",
    stock: 67,
    itemId: "ARP-7891",
    itemsSold: 598,
    sales: 38945,
    status: "in-stock",
    rating: 4.5,
    reviews: 189,
    createdAt: "2024-01-11",
    updatedAt: "2024-01-17",
    color: "black",
  },
  {
    id: "8",
    name: "Wireless Keyboard",
    description: "Mechanical wireless keyboard",
    price: 149.99,
    category: "Electronics",
    brand: "KeyTech",
    image: "/images/products/keyboard.jpg",
    stock: 28,
    itemId: "ARP-4562",
    itemsSold: 543,
    sales: 32450,
    status: "low-stock",
    rating: 4.3,
    reviews: 112,
    createdAt: "2024-01-13",
    updatedAt: "2024-01-20",
    color: "black",
  },
  {
    id: "9",
    name: "Bluetooth Speaker",
    description: "Portable bluetooth speaker with bass",
    price: 89.99,
    category: "Electronics",
    brand: "SoundTech",
    image: "/images/products/speaker.jpg",
    stock: 41,
    itemId: "ARP-2341",
    itemsSold: 487,
    sales: 28900,
    status: "in-stock",
    rating: 4.1,
    reviews: 98,
    createdAt: "2024-01-09",
    updatedAt: "2024-01-18",
    color: "black",
  },
  {
    id: "10",
    name: "Power Bank",
    description: "10000mAh portable charger",
    price: 49.99,
    category: "Electronics",
    brand: "PowerTech",
    image: "/images/products/powerbank.jpg",
    stock: 89,
    itemId: "ARP-5678",
    itemsSold: 432,
    sales: 25600,
    status: "in-stock",
    rating: 4.4,
    reviews: 145,
    createdAt: "2024-01-16",
    updatedAt: "2024-01-21",
    color: "black",
  },
];
