import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import DashboardLayout from "@/shared/components/layouts/DashboardLayout";

import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased dark:bg-background`}>
        <DashboardLayout>{children}</DashboardLayout>
      </body>
    </html>
  );
}
