import { Product } from "@/features/ecommerce/types";

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Wireless Bluetooth Headphones",
    description: "High-quality wireless headphones with noise cancellation",
    price: 129.99,
    originalPrice: 159.99,
    category: "Electronics",
    brand: "AudioTech",
    image: "/images/products/wireless-headphone.jpg",
    stock: 45,
    status: "in-stock",
    rating: 4.5,
    reviews: 128,
    createdAt: "2024-01-15",
    updatedAt: "2024-01-20",
    color: "black",
    itemsFor: "unisex", // Yeni field eklendi
  },
  {
    id: "2",
    name: "Smart Fitness Watch",
    description: "Track your health and fitness goals",
    price: 199.99,
    category: "Wearables",
    brand: "FitTech",
    image: "/images/products/smart-fitness-watch.jpg",
    stock: 12,
    status: "low-stock",
    rating: 4.2,
    reviews: 89,
    createdAt: "2024-01-10",
    updatedAt: "2024-01-18",
    color: "black",
    itemsFor: "unisex",
  },
  {
    id: "3",
    name: "Organic Cotton T-Shirt",
    description: "Comfortable and eco-friendly cotton t-shirt",
    price: 29.99,
    category: "Clothing",
    brand: "EcoWear",
    image: "/images/products/organic-cotton-t-shirt.jpg",
    stock: 0,
    status: "out-of-stock",
    rating: 4.7,
    reviews: 256,
    createdAt: "2024-01-05",
    updatedAt: "2024-01-22",
    color: "white",
    itemsFor: "unisex",
  },
  {
    id: "4",
    name: "Portable Power Bank",
    description: "10000mAh portable charger for all devices",
    price: 49.99,
    originalPrice: 69.99,
    category: "Electronics",
    brand: "PowerTech",
    image: "/images/products/portable-power-bank.jpg",
    stock: 78,
    status: "in-stock",
    rating: 4.3,
    reviews: 156,
    createdAt: "2024-01-12",
    updatedAt: "2024-01-19",
    color: "black",
    itemsFor: "unisex",
  },
  {
    id: "5",
    name: "Stainless Steel Water Bottle",
    description: "Insulated water bottle keeps drinks cold for 24 hours",
    price: 34.99,
    category: "Home & Garden",
    brand: "HydroLife",
    image: "/images/products/stainless-steel-water-bottle.jpg",
    stock: 23,
    status: "low-stock",
    rating: 4.6,
    reviews: 203,
    createdAt: "2024-01-08",
    updatedAt: "2024-01-21",
    color: "blue",
    itemsFor: "unisex",
  },
  {
    id: "6",
    name: "Wireless Gaming Mouse",
    description: "High-precision gaming mouse with RGB lighting",
    price: 79.99,
    category: "Electronics",
    brand: "GameTech",
    image: "/images/products/wireless-gaming-mouse.jpg",
    stock: 34,
    status: "in-stock",
    rating: 4.4,
    reviews: 167,
    createdAt: "2024-01-14",
    updatedAt: "2024-01-20",
    color: "black",
    itemsFor: "unisex",
  },
  {
    id: "7",
    name: "Women's Running Shoes",
    description: "Comfortable running shoes for women",
    price: 89.99,
    category: "Clothing",
    brand: "SportMax",
    image: "/images/products/women-running-shoes.jpg",
    stock: 15,
    status: "in-stock",
    rating: 4.8,
    reviews: 312,
    createdAt: "2024-01-16",
    updatedAt: "2024-01-23",
    color: "pink",
    itemsFor: "women",
  },
  {
    id: "8",
    name: "Men's Leather Jacket",
    description: "Classic leather jacket for men",
    price: 199.99,
    originalPrice: 249.99,
    category: "Clothing",
    brand: "LeatherCraft",
    image: "/images/products/men-leather-jacket.jpg",
    stock: 8,
    status: "low-stock",
    rating: 4.6,
    reviews: 189,
    createdAt: "2024-01-11",
    updatedAt: "2024-01-19",
    color: "brown",
    itemsFor: "men",
  },
  {
    id: "9",
    name: "Kids' Backpack",
    description: "Colorful backpack for kids",
    price: 39.99,
    category: "Clothing",
    brand: "KidStuff",
    image: "/images/products/kids-backpack.jpg",
    stock: 25,
    status: "in-stock",
    rating: 4.3,
    reviews: 145,
    createdAt: "2024-01-13",
    updatedAt: "2024-01-21",
    color: "blue",
    itemsFor: "kids",
  },
];

export const PRODUCT_CATEGORIES = [
  "All Categories",
  "Electronics",
  "Clothing",
  "Wearables",
  "Home & Garden",
  "Sports",
  "Books",
  "Beauty",
];

export const PRODUCT_BRANDS = [
  "All Brands",
  "AudioTech",
  "FitTech",
  "EcoWear",
  "PowerTech",
  "HydroLife",
  "GameTech",
  "SmartHome",
  "SportMax",
  "LeatherCraft",
  "KidStuff",
];

export const PRODUCT_COLORS = [
  "black",
  "white",
  "red",
  "green",
  "blue",
  "orange",
  "pink",
  "purple",
  "yellow",
  "gray",
  "brown",
  "cyan",
  "lime",
  "indigo",
  "violet",
];

export const PRODUCT_ITEMS_FOR = ["men", "women", "kids", "unisex"];

export const PRODUCT_RATINGS = [1, 2, 3, 4, 5];
