import { Transaction } from "@/features/ecommerce/types";

export const TRANSACTIONS: Transaction[] = [
  {
    id: "txn-001",
    customerName: "John Doe",
    customerEmail: "john@example.com",
    customerAvatar: "/api/placeholder/32/32",
    productName: "Smart Watch Pro",
    transactionDate: "2024-01-15T10:30:00Z",
    amount: 299.99,
    status: "completed",
    paymentMethod: "Credit Card",
    orderId: "ORD-2024-001",
  },
  {
    id: "txn-002",
    customerName: "Jane Smith",
    customerEmail: "jane@example.com",
    customerAvatar: "/api/placeholder/32/32",
    productName: "Wireless Headphones",
    transactionDate: "2024-01-15T09:15:00Z",
    amount: 149.99,
    status: "completed",
    paymentMethod: "PayPal",
    orderId: "ORD-2024-002",
  },
  {
    id: "txn-003",
    customerName: "Mike Johnson",
    customerEmail: "mike@example.com",
    customerAvatar: "/api/placeholder/32/32",
    productName: "Gaming Laptop",
    transactionDate: "2024-01-15T08:45:00Z",
    amount: 1299.99,
    status: "pending",
    paymentMethod: "Bank Transfer",
    orderId: "ORD-2024-003",
  },
  {
    id: "txn-004",
    customerName: "Sarah Wilson",
    customerEmail: "sarah@example.com",
    customerAvatar: "/api/placeholder/32/32",
    productName: "Smartphone Case",
    transactionDate: "2024-01-15T07:20:00Z",
    amount: 29.99,
    status: "completed",
    paymentMethod: "Credit Card",
    orderId: "ORD-2024-004",
  },
  {
    id: "txn-005",
    customerName: "David Brown",
    customerEmail: "david@example.com",
    customerAvatar: "/api/placeholder/32/32",
    productName: "Bluetooth Speaker",
    transactionDate: "2024-01-15T06:10:00Z",
    amount: 89.99,
    status: "failed",
    paymentMethod: "Credit Card",
    orderId: "ORD-2024-005",
  },
  {
    id: "txn-006",
    customerName: "Lisa Davis",
    customerEmail: "lisa@example.com",
    customerAvatar: "/api/placeholder/32/32",
    productName: "Fitness Tracker",
    transactionDate: "2024-01-15T05:30:00Z",
    amount: 79.99,
    status: "refunded",
    paymentMethod: "PayPal",
    orderId: "ORD-2024-006",
  },
];

export const TRANSACTION_STATUS_CONFIG = {
  completed: {
    label: "Completed",
    color: "text-green-600",
    bgColor: "bg-green-100",
  },
  pending: {
    label: "Pending",
    color: "text-yellow-600",
    bgColor: "bg-yellow-100",
  },
  failed: {
    label: "Failed",
    color: "text-red-600",
    bgColor: "bg-red-100",
  },
  refunded: {
    label: "Refunded",
    color: "text-gray-600",
    bgColor: "bg-gray-100",
  },
} as const;
